pipeline {
   agent any
   stages {
       stage('Build Code') {
           steps {
               sh """
               echo "Building Artifact"
               """
           }
       }

     stage('Verify BranchCode') 
     {
      when 
      {
      branch 'stage'
      }
      steps {
               sh """
               echo "Only for stage branch"
               """
           }
       }

      stage('Deploy Code') {
          steps {
               sh """
               echo "Deploying Code"
               """
          }
      }
   }
}
